baseURL = "https://pengbin.github.io/"
languageCode = "en-us"
title = "Peng Bin's Blog"
theme = "m10c"

[params]
  author = "Peng Bin"
  description = "Welcome to my blog, where coding expertise meets daily reflections. Explore insightful tech analyses, musings on work-life balance, summaries of inspiring reads, and thoughtful parenting ideas. Engaging content in both English and Chinese awaits you in this unique intersection of technology and life."

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "linkedin.com/in/bin-peng-4842065"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_ChrisJHart"i

 [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/pengbin2015"
