title = ""
baseURL = "https://pengbin.org"
languageCode = "en-us"
theme = ["ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "pengbin-org"

[languages]
  [languages.en]
    title = "Peng Bin's Blog"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.zh]
    title = "彭斌的博客"
    weight = 2
    contentDir = "content/zh"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 80

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 90

[params]
  text_color = ""
  author = "Peng Bin"
  favicon = ""
  site_logo = ""
  TIMEZONE = "Asia/Singapore"
  date_format = "2. January 2006"
  description = "Software developer, open-source enthusiast, life adventurer | This is Peng Bin's blog, dedicated to unveiling the boundless wonders of the world"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  commentoEnable = true
  featured_image = "/images/home-bg-valley.jpg"
  read_more_copy = "Read more ..."

[params.ananke_socials]
    [params.ananke_socials.twitter]
      name = "twitter"
      url = "https://twitter.com/binpengwalker"
      color = "#008cff"
    [params.ananke_socials.github]
      name = "github"
      url = "https://github.com/pengbin2015"
      color = "#008cff"
    [params.ananke_socials.linkedin]
      name = "linkedin"
      url = "https://www.linkedin.com/in/bin-peng-4842065"
      color = "#008cff"